services:
  db:
    container_name: db-betalent
    image: mysql:9.0.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - betalent

  api:
    container_name: api-betalent
    build: .
    restart: always
    env_file:
      - .env
    command: npm run dev
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    networks:
      - betalent
    volumes:
      - .:/app

volumes:
  mysql:


networks:
  betalent:
    driver: bridge
