services:
  db:
    container_name: db-betalent
    image: mysql:9.0.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:${DB_PORT}
    depends_on:
      - 'redis'

  redis:
    image: redis:7.2.5-alpine3.20
    container_name: redis
    ports:
      - 6379:6379
volumes:
  mysql:
